/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Engin;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nicno90
 */
public class MakeAttack extends javax.swing.JFrame
{

    /**
     * Creates new form MakeAttack
     */
    public MakeAttack()
    {
        initComponents();
    }

    
    public void toggle(javax.swing.JButton j)
    {
        if (j.getText().equals("O"))
        {
            j.setText("X");
        }
        else if (j.getText().equals("X"))
        {
            j.setText(">");
        }
        else if (j.getText().equals(">"))
        {
            j.setText("<");
        }
        else if (j.getText().equals("<"))
        {
            j.setText("^");
        }
        else if (j.getText().equals("^"))
        {
            j.setText("/");
        }
        else if (j.getText().equals("/"))
        {
            j.setText("O");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jS1 = new javax.swing.JButton();
        jS2 = new javax.swing.JButton();
        jS3 = new javax.swing.JButton();
        jS4 = new javax.swing.JButton();
        jS5 = new javax.swing.JButton();
        jS6 = new javax.swing.JButton();
        jS7 = new javax.swing.JButton();
        jS8 = new javax.swing.JButton();
        jS9 = new javax.swing.JButton();
        jS10 = new javax.swing.JButton();
        jS11 = new javax.swing.JButton();
        jS12 = new javax.swing.JButton();
        jS13 = new javax.swing.JButton();
        jS14 = new javax.swing.JButton();
        jS15 = new javax.swing.JButton();
        jS16 = new javax.swing.JButton();
        jS17 = new javax.swing.JButton();
        jS18 = new javax.swing.JButton();
        jS19 = new javax.swing.JButton();
        jS20 = new javax.swing.JButton();
        jS21 = new javax.swing.JButton();
        jS22 = new javax.swing.JButton();
        jS23 = new javax.swing.JButton();
        jS24 = new javax.swing.JButton();
        jS25 = new javax.swing.JButton();
        jS26 = new javax.swing.JButton();
        jS27 = new javax.swing.JButton();
        jS28 = new javax.swing.JButton();
        jS29 = new javax.swing.JButton();
        jS30 = new javax.swing.JButton();
        jS31 = new javax.swing.JButton();
        jS32 = new javax.swing.JButton();
        jS33 = new javax.swing.JButton();
        jS34 = new javax.swing.JButton();
        jS35 = new javax.swing.JButton();
        jS36 = new javax.swing.JButton();
        jS37 = new javax.swing.JButton();
        jS38 = new javax.swing.JButton();
        jS39 = new javax.swing.JButton();
        jS40 = new javax.swing.JButton();
        jS41 = new javax.swing.JButton();
        jS42 = new javax.swing.JButton();
        jS43 = new javax.swing.JButton();
        jS44 = new javax.swing.JButton();
        jS45 = new javax.swing.JButton();
        jS46 = new javax.swing.JButton();
        jS47 = new javax.swing.JButton();
        jS48 = new javax.swing.JButton();
        jS49 = new javax.swing.JButton();
        jS50 = new javax.swing.JButton();
        jS51 = new javax.swing.JButton();
        jS52 = new javax.swing.JButton();
        jS53 = new javax.swing.JButton();
        jS54 = new javax.swing.JButton();
        jS55 = new javax.swing.JButton();
        jS56 = new javax.swing.JButton();
        jS57 = new javax.swing.JButton();
        jS58 = new javax.swing.JButton();
        jS59 = new javax.swing.JButton();
        jS60 = new javax.swing.JButton();
        jS61 = new javax.swing.JButton();
        jS62 = new javax.swing.JButton();
        jS63 = new javax.swing.JButton();
        jS64 = new javax.swing.JButton();
        jS65 = new javax.swing.JButton();
        jS66 = new javax.swing.JButton();
        jS67 = new javax.swing.JButton();
        jS68 = new javax.swing.JButton();
        jS69 = new javax.swing.JButton();
        jS70 = new javax.swing.JButton();
        jS71 = new javax.swing.JButton();
        jS72 = new javax.swing.JButton();
        jS73 = new javax.swing.JButton();
        jS74 = new javax.swing.JButton();
        jS75 = new javax.swing.JButton();
        jS76 = new javax.swing.JButton();
        jS77 = new javax.swing.JButton();
        jS78 = new javax.swing.JButton();
        jS79 = new javax.swing.JButton();
        jS80 = new javax.swing.JButton();
        jS81 = new javax.swing.JButton();
        Done = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jS1.setText("O");
        jS1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS1ActionPerformed(evt);
            }
        });

        jS2.setText("O");
        jS2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS2ActionPerformed(evt);
            }
        });

        jS3.setText("O");
        jS3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS3ActionPerformed(evt);
            }
        });

        jS4.setText("O");
        jS4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS4ActionPerformed(evt);
            }
        });

        jS5.setText("O");
        jS5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS5ActionPerformed(evt);
            }
        });

        jS6.setText("O");
        jS6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS6ActionPerformed(evt);
            }
        });

        jS7.setText("O");
        jS7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS7ActionPerformed(evt);
            }
        });

        jS8.setText("O");
        jS8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS8ActionPerformed(evt);
            }
        });

        jS9.setText("O");
        jS9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS9ActionPerformed(evt);
            }
        });

        jS10.setText("O");
        jS10.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS10ActionPerformed(evt);
            }
        });

        jS11.setText("O");
        jS11.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS11ActionPerformed(evt);
            }
        });

        jS12.setText("O");
        jS12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS12ActionPerformed(evt);
            }
        });

        jS13.setText("O");
        jS13.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS13ActionPerformed(evt);
            }
        });

        jS14.setText("O");
        jS14.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS14ActionPerformed(evt);
            }
        });

        jS15.setText("O");
        jS15.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS15ActionPerformed(evt);
            }
        });

        jS16.setText("O");
        jS16.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS16ActionPerformed(evt);
            }
        });

        jS17.setText("O");
        jS17.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS17ActionPerformed(evt);
            }
        });

        jS18.setText("O");
        jS18.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS18ActionPerformed(evt);
            }
        });

        jS19.setText("O");
        jS19.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS19ActionPerformed(evt);
            }
        });

        jS20.setText("O");
        jS20.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS20ActionPerformed(evt);
            }
        });

        jS21.setText("O");
        jS21.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS21ActionPerformed(evt);
            }
        });

        jS22.setText("O");
        jS22.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS22ActionPerformed(evt);
            }
        });

        jS23.setText("O");
        jS23.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS23ActionPerformed(evt);
            }
        });

        jS24.setText("O");
        jS24.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS24ActionPerformed(evt);
            }
        });

        jS25.setText("O");
        jS25.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS25ActionPerformed(evt);
            }
        });

        jS26.setText("O");
        jS26.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS26ActionPerformed(evt);
            }
        });

        jS27.setText("O");
        jS27.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS27ActionPerformed(evt);
            }
        });

        jS28.setText("O");
        jS28.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS28ActionPerformed(evt);
            }
        });

        jS29.setText("O");
        jS29.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS29ActionPerformed(evt);
            }
        });

        jS30.setText("O");
        jS30.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS30ActionPerformed(evt);
            }
        });

        jS31.setText("O");
        jS31.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS31ActionPerformed(evt);
            }
        });

        jS32.setText("O");
        jS32.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS32ActionPerformed(evt);
            }
        });

        jS33.setText("O");
        jS33.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS33ActionPerformed(evt);
            }
        });

        jS34.setText("O");
        jS34.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS34ActionPerformed(evt);
            }
        });

        jS35.setText("O");
        jS35.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS35ActionPerformed(evt);
            }
        });

        jS36.setText("O");
        jS36.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS36ActionPerformed(evt);
            }
        });

        jS37.setText("O");
        jS37.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS37ActionPerformed(evt);
            }
        });

        jS38.setText("O");
        jS38.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS38ActionPerformed(evt);
            }
        });

        jS39.setText("O");
        jS39.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS39ActionPerformed(evt);
            }
        });

        jS40.setText("O");
        jS40.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS40ActionPerformed(evt);
            }
        });

        jS41.setText("P");

        jS42.setText("O");
        jS42.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS42ActionPerformed(evt);
            }
        });

        jS43.setText("O");
        jS43.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS43ActionPerformed(evt);
            }
        });

        jS44.setText("O");
        jS44.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS44ActionPerformed(evt);
            }
        });

        jS45.setText("O");
        jS45.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS45ActionPerformed(evt);
            }
        });

        jS46.setText("O");
        jS46.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS46ActionPerformed(evt);
            }
        });

        jS47.setText("O");
        jS47.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS47ActionPerformed(evt);
            }
        });

        jS48.setText("O");
        jS48.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS48ActionPerformed(evt);
            }
        });

        jS49.setText("O");
        jS49.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS49ActionPerformed(evt);
            }
        });

        jS50.setText("O");
        jS50.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS50ActionPerformed(evt);
            }
        });

        jS51.setText("O");
        jS51.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS51ActionPerformed(evt);
            }
        });

        jS52.setText("O");
        jS52.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS52ActionPerformed(evt);
            }
        });

        jS53.setText("O");
        jS53.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS53ActionPerformed(evt);
            }
        });

        jS54.setText("O");
        jS54.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS54ActionPerformed(evt);
            }
        });

        jS55.setText("O");
        jS55.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS55ActionPerformed(evt);
            }
        });

        jS56.setText("O");
        jS56.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS56ActionPerformed(evt);
            }
        });

        jS57.setText("O");
        jS57.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS57ActionPerformed(evt);
            }
        });

        jS58.setText("O");
        jS58.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS58ActionPerformed(evt);
            }
        });

        jS59.setText("O");
        jS59.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS59ActionPerformed(evt);
            }
        });

        jS60.setText("O");
        jS60.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS60ActionPerformed(evt);
            }
        });

        jS61.setText("O");
        jS61.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS61ActionPerformed(evt);
            }
        });

        jS62.setText("O");
        jS62.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS62ActionPerformed(evt);
            }
        });

        jS63.setText("O");
        jS63.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS63ActionPerformed(evt);
            }
        });

        jS64.setText("O");
        jS64.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS64ActionPerformed(evt);
            }
        });

        jS65.setText("O");
        jS65.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS65ActionPerformed(evt);
            }
        });

        jS66.setText("O");
        jS66.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS66ActionPerformed(evt);
            }
        });

        jS67.setText("O");
        jS67.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS67ActionPerformed(evt);
            }
        });

        jS68.setText("O");
        jS68.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS68ActionPerformed(evt);
            }
        });

        jS69.setText("O");
        jS69.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS69ActionPerformed(evt);
            }
        });

        jS70.setText("O");
        jS70.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS70ActionPerformed(evt);
            }
        });

        jS71.setText("O");
        jS71.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS71ActionPerformed(evt);
            }
        });

        jS72.setText("O");
        jS72.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS72ActionPerformed(evt);
            }
        });

        jS73.setText("O");
        jS73.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS73ActionPerformed(evt);
            }
        });

        jS74.setText("O");
        jS74.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS74ActionPerformed(evt);
            }
        });

        jS75.setText("O");
        jS75.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS75ActionPerformed(evt);
            }
        });

        jS76.setText("O");
        jS76.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS76ActionPerformed(evt);
            }
        });

        jS77.setText("O");
        jS77.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS77ActionPerformed(evt);
            }
        });

        jS78.setText("O");
        jS78.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS78ActionPerformed(evt);
            }
        });

        jS79.setText("O");
        jS79.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS79ActionPerformed(evt);
            }
        });

        jS80.setText("O");
        jS80.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS80ActionPerformed(evt);
            }
        });

        jS81.setText("O");
        jS81.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jS81ActionPerformed(evt);
            }
        });

        Done.setText("Done");
        Done.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DoneActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Diagonal");

        jTextField1.setText("Name (Camle case)");
        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Done, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jS28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jS37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jS55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS58, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS59, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jS1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jS10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jS19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jS46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jS64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS67, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS68, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS69, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS70, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS71, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS72, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jS73, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jS74, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCheckBox1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jS75, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jS76, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jS77, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jS78, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS79, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS80, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jS81, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jS1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jS10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jS19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS26, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS27, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jS28, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS35, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS36, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jS37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS38, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS39, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS40, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS41, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS42, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS43, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS45, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jS46, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS47, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS48, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS49, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS50, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS51, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS52, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS53, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS54, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jS55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS56, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS57, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS58, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS59, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS61, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS62, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS63, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jS64, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS65, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS67, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS68, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS69, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS70, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS71, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS72, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jS73, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS74, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS75, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS76, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS77, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS78, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS79, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS80, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS81, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(Done, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jS1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS1ActionPerformed
    {//GEN-HEADEREND:event_jS1ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS1);
    }//GEN-LAST:event_jS1ActionPerformed

    private void jS2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS2ActionPerformed
    {//GEN-HEADEREND:event_jS2ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS2);
    }//GEN-LAST:event_jS2ActionPerformed

    private void jS3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS3ActionPerformed
    {//GEN-HEADEREND:event_jS3ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS3);
    }//GEN-LAST:event_jS3ActionPerformed

    private void jS4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS4ActionPerformed
    {//GEN-HEADEREND:event_jS4ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS4);
    }//GEN-LAST:event_jS4ActionPerformed

    private void jS5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS5ActionPerformed
    {//GEN-HEADEREND:event_jS5ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS5);
    }//GEN-LAST:event_jS5ActionPerformed

    private void jS6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS6ActionPerformed
    {//GEN-HEADEREND:event_jS6ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS6);
    }//GEN-LAST:event_jS6ActionPerformed

    private void jS7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS7ActionPerformed
    {//GEN-HEADEREND:event_jS7ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS7);
    }//GEN-LAST:event_jS7ActionPerformed

    private void jS8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS8ActionPerformed
    {//GEN-HEADEREND:event_jS8ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS8);
    }//GEN-LAST:event_jS8ActionPerformed

    private void jS9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS9ActionPerformed
    {//GEN-HEADEREND:event_jS9ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS9);
    }//GEN-LAST:event_jS9ActionPerformed

    private void jS10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS10ActionPerformed
    {//GEN-HEADEREND:event_jS10ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS10);
    }//GEN-LAST:event_jS10ActionPerformed

    private void jS11ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS11ActionPerformed
    {//GEN-HEADEREND:event_jS11ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS11);
    }//GEN-LAST:event_jS11ActionPerformed

    private void jS12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS12ActionPerformed
    {//GEN-HEADEREND:event_jS12ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS12);
    }//GEN-LAST:event_jS12ActionPerformed

    private void jS13ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS13ActionPerformed
    {//GEN-HEADEREND:event_jS13ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS13);
    }//GEN-LAST:event_jS13ActionPerformed

    private void jS14ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS14ActionPerformed
    {//GEN-HEADEREND:event_jS14ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS14);
    }//GEN-LAST:event_jS14ActionPerformed

    private void jS15ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS15ActionPerformed
    {//GEN-HEADEREND:event_jS15ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS15);
    }//GEN-LAST:event_jS15ActionPerformed

    private void jS16ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS16ActionPerformed
    {//GEN-HEADEREND:event_jS16ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS16);
    }//GEN-LAST:event_jS16ActionPerformed

    private void jS17ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS17ActionPerformed
    {//GEN-HEADEREND:event_jS17ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS17);
    }//GEN-LAST:event_jS17ActionPerformed

    private void jS18ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS18ActionPerformed
    {//GEN-HEADEREND:event_jS18ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS18);
    }//GEN-LAST:event_jS18ActionPerformed

    private void jS19ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS19ActionPerformed
    {//GEN-HEADEREND:event_jS19ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS19);
    }//GEN-LAST:event_jS19ActionPerformed

    private void jS20ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS20ActionPerformed
    {//GEN-HEADEREND:event_jS20ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS20);
    }//GEN-LAST:event_jS20ActionPerformed

    private void jS21ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS21ActionPerformed
    {//GEN-HEADEREND:event_jS21ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS21);
    }//GEN-LAST:event_jS21ActionPerformed

    private void jS22ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS22ActionPerformed
    {//GEN-HEADEREND:event_jS22ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS22);
    }//GEN-LAST:event_jS22ActionPerformed

    private void jS23ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS23ActionPerformed
    {//GEN-HEADEREND:event_jS23ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS23);
    }//GEN-LAST:event_jS23ActionPerformed

    private void jS24ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS24ActionPerformed
    {//GEN-HEADEREND:event_jS24ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS24);
    }//GEN-LAST:event_jS24ActionPerformed

    private void jS25ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS25ActionPerformed
    {//GEN-HEADEREND:event_jS25ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS25);
    }//GEN-LAST:event_jS25ActionPerformed

    private void jS26ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS26ActionPerformed
    {//GEN-HEADEREND:event_jS26ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS26);
    }//GEN-LAST:event_jS26ActionPerformed

    private void jS27ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS27ActionPerformed
    {//GEN-HEADEREND:event_jS27ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS27);
    }//GEN-LAST:event_jS27ActionPerformed

    private void jS28ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS28ActionPerformed
    {//GEN-HEADEREND:event_jS28ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS28);
    }//GEN-LAST:event_jS28ActionPerformed

    private void jS29ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS29ActionPerformed
    {//GEN-HEADEREND:event_jS29ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS29);
    }//GEN-LAST:event_jS29ActionPerformed

    private void jS30ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS30ActionPerformed
    {//GEN-HEADEREND:event_jS30ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS30);
    }//GEN-LAST:event_jS30ActionPerformed

    private void jS31ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS31ActionPerformed
    {//GEN-HEADEREND:event_jS31ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS31);
    }//GEN-LAST:event_jS31ActionPerformed

    private void jS32ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS32ActionPerformed
    {//GEN-HEADEREND:event_jS32ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS32);
    }//GEN-LAST:event_jS32ActionPerformed

    private void jS33ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS33ActionPerformed
    {//GEN-HEADEREND:event_jS33ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS33);
    }//GEN-LAST:event_jS33ActionPerformed

    private void jS34ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS34ActionPerformed
    {//GEN-HEADEREND:event_jS34ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS34);
    }//GEN-LAST:event_jS34ActionPerformed

    private void jS35ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS35ActionPerformed
    {//GEN-HEADEREND:event_jS35ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS35);
    }//GEN-LAST:event_jS35ActionPerformed

    private void jS36ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS36ActionPerformed
    {//GEN-HEADEREND:event_jS36ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS36);
    }//GEN-LAST:event_jS36ActionPerformed

    private void jS37ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS37ActionPerformed
    {//GEN-HEADEREND:event_jS37ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS37);
    }//GEN-LAST:event_jS37ActionPerformed

    private void jS38ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS38ActionPerformed
    {//GEN-HEADEREND:event_jS38ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS38);
    }//GEN-LAST:event_jS38ActionPerformed

    private void jS39ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS39ActionPerformed
    {//GEN-HEADEREND:event_jS39ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS39);
    }//GEN-LAST:event_jS39ActionPerformed

    private void jS40ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS40ActionPerformed
    {//GEN-HEADEREND:event_jS40ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS40);
    }//GEN-LAST:event_jS40ActionPerformed

    private void jS42ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS42ActionPerformed
    {//GEN-HEADEREND:event_jS42ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS42);
    }//GEN-LAST:event_jS42ActionPerformed

    private void jS43ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS43ActionPerformed
    {//GEN-HEADEREND:event_jS43ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS43);
    }//GEN-LAST:event_jS43ActionPerformed

    private void jS44ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS44ActionPerformed
    {//GEN-HEADEREND:event_jS44ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS44);
    }//GEN-LAST:event_jS44ActionPerformed

    private void jS45ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS45ActionPerformed
    {//GEN-HEADEREND:event_jS45ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS45);
    }//GEN-LAST:event_jS45ActionPerformed

    private void jS46ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS46ActionPerformed
    {//GEN-HEADEREND:event_jS46ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS46);
    }//GEN-LAST:event_jS46ActionPerformed

    private void jS47ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS47ActionPerformed
    {//GEN-HEADEREND:event_jS47ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS47);
    }//GEN-LAST:event_jS47ActionPerformed

    private void jS48ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS48ActionPerformed
    {//GEN-HEADEREND:event_jS48ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS48);
    }//GEN-LAST:event_jS48ActionPerformed

    private void jS49ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS49ActionPerformed
    {//GEN-HEADEREND:event_jS49ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS49);
    }//GEN-LAST:event_jS49ActionPerformed

    private void jS50ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS50ActionPerformed
    {//GEN-HEADEREND:event_jS50ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS50);
    }//GEN-LAST:event_jS50ActionPerformed

    private void jS51ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS51ActionPerformed
    {//GEN-HEADEREND:event_jS51ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS51);
    }//GEN-LAST:event_jS51ActionPerformed

    private void jS52ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS52ActionPerformed
    {//GEN-HEADEREND:event_jS52ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS52);
    }//GEN-LAST:event_jS52ActionPerformed

    private void jS53ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS53ActionPerformed
    {//GEN-HEADEREND:event_jS53ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS53);
    }//GEN-LAST:event_jS53ActionPerformed

    private void jS54ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS54ActionPerformed
    {//GEN-HEADEREND:event_jS54ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS54);
    }//GEN-LAST:event_jS54ActionPerformed

    private void jS55ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS55ActionPerformed
    {//GEN-HEADEREND:event_jS55ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS55);
    }//GEN-LAST:event_jS55ActionPerformed

    private void jS56ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS56ActionPerformed
    {//GEN-HEADEREND:event_jS56ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS56);
    }//GEN-LAST:event_jS56ActionPerformed

    private void jS57ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS57ActionPerformed
    {//GEN-HEADEREND:event_jS57ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS57);
    }//GEN-LAST:event_jS57ActionPerformed

    private void jS58ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS58ActionPerformed
    {//GEN-HEADEREND:event_jS58ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS58);
    }//GEN-LAST:event_jS58ActionPerformed

    private void jS59ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS59ActionPerformed
    {//GEN-HEADEREND:event_jS59ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS59);
    }//GEN-LAST:event_jS59ActionPerformed

    private void jS60ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS60ActionPerformed
    {//GEN-HEADEREND:event_jS60ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS60);
    }//GEN-LAST:event_jS60ActionPerformed

    private void jS61ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS61ActionPerformed
    {//GEN-HEADEREND:event_jS61ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS61);
    }//GEN-LAST:event_jS61ActionPerformed

    private void jS62ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS62ActionPerformed
    {//GEN-HEADEREND:event_jS62ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS62);
    }//GEN-LAST:event_jS62ActionPerformed

    private void jS63ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS63ActionPerformed
    {//GEN-HEADEREND:event_jS63ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS63);
    }//GEN-LAST:event_jS63ActionPerformed

    private void jS64ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS64ActionPerformed
    {//GEN-HEADEREND:event_jS64ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS64);
    }//GEN-LAST:event_jS64ActionPerformed

    private void jS65ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS65ActionPerformed
    {//GEN-HEADEREND:event_jS65ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS65);
    }//GEN-LAST:event_jS65ActionPerformed

    private void jS66ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS66ActionPerformed
    {//GEN-HEADEREND:event_jS66ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS66);
    }//GEN-LAST:event_jS66ActionPerformed

    private void jS67ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS67ActionPerformed
    {//GEN-HEADEREND:event_jS67ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS67);
    }//GEN-LAST:event_jS67ActionPerformed

    private void jS68ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS68ActionPerformed
    {//GEN-HEADEREND:event_jS68ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS68);
    }//GEN-LAST:event_jS68ActionPerformed

    private void jS69ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS69ActionPerformed
    {//GEN-HEADEREND:event_jS69ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS69);
    }//GEN-LAST:event_jS69ActionPerformed

    private void jS70ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS70ActionPerformed
    {//GEN-HEADEREND:event_jS70ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS70);
    }//GEN-LAST:event_jS70ActionPerformed

    private void jS71ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS71ActionPerformed
    {//GEN-HEADEREND:event_jS71ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS71);
    }//GEN-LAST:event_jS71ActionPerformed

    private void jS72ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS72ActionPerformed
    {//GEN-HEADEREND:event_jS72ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS72);
    }//GEN-LAST:event_jS72ActionPerformed

    private void jS73ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS73ActionPerformed
    {//GEN-HEADEREND:event_jS73ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS73);
    }//GEN-LAST:event_jS73ActionPerformed

    private void jS74ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS74ActionPerformed
    {//GEN-HEADEREND:event_jS74ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS74);
    }//GEN-LAST:event_jS74ActionPerformed

    private void jS75ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS75ActionPerformed
    {//GEN-HEADEREND:event_jS75ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS75);
    }//GEN-LAST:event_jS75ActionPerformed

    private void jS76ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS76ActionPerformed
    {//GEN-HEADEREND:event_jS76ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS76);
    }//GEN-LAST:event_jS76ActionPerformed

    private void jS77ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS77ActionPerformed
    {//GEN-HEADEREND:event_jS77ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS77);
    }//GEN-LAST:event_jS77ActionPerformed

    private void jS78ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS78ActionPerformed
    {//GEN-HEADEREND:event_jS78ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS78);
    }//GEN-LAST:event_jS78ActionPerformed

    private void jS79ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS79ActionPerformed
    {//GEN-HEADEREND:event_jS79ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS79);
    }//GEN-LAST:event_jS79ActionPerformed

    private void jS80ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS80ActionPerformed
    {//GEN-HEADEREND:event_jS80ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS80);
    }//GEN-LAST:event_jS80ActionPerformed

    private void jS81ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jS81ActionPerformed
    {//GEN-HEADEREND:event_jS81ActionPerformed
        // TODO add your handling code here:
        toggle(this.jS81);
    }//GEN-LAST:event_jS81ActionPerformed

    private void DoneActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DoneActionPerformed
    {//GEN-HEADEREND:event_DoneActionPerformed
        // TODO add your handling code here:
        String s = "";
        
        s += this.jS1.getText();
        s += this.jS2.getText();
        s += this.jS3.getText();
        s += this.jS4.getText();
        s += this.jS5.getText();
        s += this.jS6.getText();
        s += this.jS7.getText();
        s += this.jS8.getText();
        s += this.jS9.getText();
        s += "\n";
        s += this.jS10.getText();
        s += this.jS11.getText();
        s += this.jS12.getText();
        s += this.jS13.getText();
        s += this.jS14.getText();
        s += this.jS15.getText();
        s += this.jS16.getText();
        s += this.jS17.getText();
        s += this.jS18.getText();
        s += "\n";
        s += this.jS19.getText();
        s += this.jS20.getText();
        s += this.jS21.getText();
        s += this.jS22.getText();
        s += this.jS23.getText();
        s += this.jS24.getText();
        s += this.jS25.getText();
        s += this.jS26.getText();
        s += this.jS27.getText();
        s += "\n";
        s += this.jS28.getText();
        s += this.jS29.getText();
        s += this.jS30.getText();
        s += this.jS31.getText();
        s += this.jS32.getText();
        s += this.jS33.getText();
        s += this.jS34.getText();
        s += this.jS35.getText();
        s += this.jS36.getText();
        s += "\n";
        s += this.jS37.getText();
        s += this.jS38.getText();
        s += this.jS39.getText();
        s += this.jS40.getText();
        s += this.jS41.getText();
        s += this.jS42.getText();
        s += this.jS43.getText();
        s += this.jS44.getText();
        s += this.jS45.getText();
        s += "\n";
        s += this.jS46.getText();
        s += this.jS47.getText();
        s += this.jS48.getText();
        s += this.jS49.getText();
        s += this.jS50.getText();
        s += this.jS51.getText();
        s += this.jS52.getText();
        s += this.jS53.getText();
        s += this.jS54.getText();
        s += "\n";
        s += this.jS55.getText();
        s += this.jS56.getText();
        s += this.jS57.getText();
        s += this.jS58.getText();
        s += this.jS59.getText();
        s += this.jS60.getText();
        s += this.jS61.getText();
        s += this.jS62.getText();
        s += this.jS63.getText();
        s += "\n";
        s += this.jS64.getText();
        s += this.jS65.getText();
        s += this.jS66.getText();
        s += this.jS67.getText();
        s += this.jS68.getText();
        s += this.jS69.getText();
        s += this.jS70.getText();
        s += this.jS71.getText();
        s += this.jS72.getText();
        s += "\n";
        s += this.jS73.getText();
        s += this.jS74.getText();
        s += this.jS75.getText();
        s += this.jS76.getText();
        s += this.jS77.getText();
        s += this.jS78.getText();
        s += this.jS79.getText();
        s += this.jS80.getText();
        s += this.jS81.getText();
        
        File f = new File("C:\\Users\\nicno90\\Documents\\NetBeansProjects\\Server\\src\\Attacks\\" + this.jTextField1.getText() + ".txt");
        PrintWriter writer = null;
        try
        {
            writer = new PrintWriter(f);
        } catch (FileNotFoundException ex)
        {
            Logger.getLogger(AddItem.class.getName()).log(Level.SEVERE, null, ex);
        }
        writer.print(s);
        writer.close();
        if (ctr == 1)
        {
            this.main(new String[1]);
            ctr--;
        }
        this.dispose();
        
        
    }//GEN-LAST:event_DoneActionPerformed
    private static int ctr = 1;
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MakeAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MakeAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MakeAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MakeAttack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MakeAttack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Done;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JButton jS1;
    private javax.swing.JButton jS10;
    private javax.swing.JButton jS11;
    private javax.swing.JButton jS12;
    private javax.swing.JButton jS13;
    private javax.swing.JButton jS14;
    private javax.swing.JButton jS15;
    private javax.swing.JButton jS16;
    private javax.swing.JButton jS17;
    private javax.swing.JButton jS18;
    private javax.swing.JButton jS19;
    private javax.swing.JButton jS2;
    private javax.swing.JButton jS20;
    private javax.swing.JButton jS21;
    private javax.swing.JButton jS22;
    private javax.swing.JButton jS23;
    private javax.swing.JButton jS24;
    private javax.swing.JButton jS25;
    private javax.swing.JButton jS26;
    private javax.swing.JButton jS27;
    private javax.swing.JButton jS28;
    private javax.swing.JButton jS29;
    private javax.swing.JButton jS3;
    private javax.swing.JButton jS30;
    private javax.swing.JButton jS31;
    private javax.swing.JButton jS32;
    private javax.swing.JButton jS33;
    private javax.swing.JButton jS34;
    private javax.swing.JButton jS35;
    private javax.swing.JButton jS36;
    private javax.swing.JButton jS37;
    private javax.swing.JButton jS38;
    private javax.swing.JButton jS39;
    private javax.swing.JButton jS4;
    private javax.swing.JButton jS40;
    private javax.swing.JButton jS41;
    private javax.swing.JButton jS42;
    private javax.swing.JButton jS43;
    private javax.swing.JButton jS44;
    private javax.swing.JButton jS45;
    private javax.swing.JButton jS46;
    private javax.swing.JButton jS47;
    private javax.swing.JButton jS48;
    private javax.swing.JButton jS49;
    private javax.swing.JButton jS5;
    private javax.swing.JButton jS50;
    private javax.swing.JButton jS51;
    private javax.swing.JButton jS52;
    private javax.swing.JButton jS53;
    private javax.swing.JButton jS54;
    private javax.swing.JButton jS55;
    private javax.swing.JButton jS56;
    private javax.swing.JButton jS57;
    private javax.swing.JButton jS58;
    private javax.swing.JButton jS59;
    private javax.swing.JButton jS6;
    private javax.swing.JButton jS60;
    private javax.swing.JButton jS61;
    private javax.swing.JButton jS62;
    private javax.swing.JButton jS63;
    private javax.swing.JButton jS64;
    private javax.swing.JButton jS65;
    private javax.swing.JButton jS66;
    private javax.swing.JButton jS67;
    private javax.swing.JButton jS68;
    private javax.swing.JButton jS69;
    private javax.swing.JButton jS7;
    private javax.swing.JButton jS70;
    private javax.swing.JButton jS71;
    private javax.swing.JButton jS72;
    private javax.swing.JButton jS73;
    private javax.swing.JButton jS74;
    private javax.swing.JButton jS75;
    private javax.swing.JButton jS76;
    private javax.swing.JButton jS77;
    private javax.swing.JButton jS78;
    private javax.swing.JButton jS79;
    private javax.swing.JButton jS8;
    private javax.swing.JButton jS80;
    private javax.swing.JButton jS81;
    private javax.swing.JButton jS9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
